spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
        access-key: 
        secret-key: 
        oss:
          endpoint: oss-ap-northeast-1.aliyuncs.com
          bucket: gulimall-tokyo
  application:
    name: gulimall-third-party

server:
  port: 30000
